### ISSUE TITLE
Wrong message length computation on Big Endian platforms (Solaris)

### ISSUE THREAD

**Issue by KarlikB** [winebarrel/zabbix_protocol#3]
The zabbix_protocol does not work on Solaris.

The zabbix sender protocol contains binary message length field encoded as little endian.

The file zabbix_protocol.rb encodes/decodes string to binary using pack/unpack methods. 
E.g:
[payload.length].pack('Q'),
payload_len = payload_len.unpack("Q").first

The "Q" directive means that the string will be encoded as uint64_t NATIVE endian.
This mean that the data is encoded as Big Endian on the Solaris and are consequently rejected by Zabbix. 

Solution is to replace "Q" directives by "Q<" directives in the code, e.g.:
[payload.length].pack('Q<'),
payload_len = payload_len.unpack("Q<").first
The "Q<" directive means uint64_t little endian

After this change, the code works also on Solaris (big endian platform).

**Comment by winebarrel** [comment]
Thanks for your report! 😃 
I have been fix it acd461cc6a5a4f9d4020736a349ad56b3cdbec05

Please try v0.1.5!

**Comment by KarlikB** [comment]
Thanks for your effort
